spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: sandbox.smtp.mailtrap.io
    username: 8efe7beb696974

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.plcoding.chirp: DEBUG