
spring:
  application:
    name: chirp

  data:
    redis:
      host: "redis-14065.crce216.sa-east-1-2.ec2.redns.redis-cloud.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 14065
      connect-timeout: 5000ms
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.qdxdchomvltnkiyswxwb
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMiB: 5

        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: jackal.rmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: zcqnfzal
    ssl:
      enabled: true
    virtual-host: zcqnfzal
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}

chirp:
  api-key:
    expires-in-days: 365
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  email:
    from: mail@pl-coding.com
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://qdxdchomvltnkiyswxwb.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials-path: "classpath:firebase-credentials/chirp-firebase-adminsdk.json"

server:
  port: 8095