spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.eu.mailgun.org
    username: mail@mg.pl-coding.com
    test-connection: true

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: false

chirp:
  email:
    url: "https://chirp.pl-coding.com"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://chirp.pl-coding.com"
  api-key-required: true

logging:
  level:
    com.plcoding.chirp: DEBUG